<?php
declare(strict_types=1);
require __DIR__ . '/includes/bootstrap.php';
require __DIR__ . '/includes/layout.php';
page_head('Política de privacidad | InnovaPro'); site_header(false);
?>
<main id="contenido" class="wrap legal-page"><a href="/">← Volver a la landing</a><h1>Política de privacidad</h1><p>Información de demo.innovapro.es. Versión <?=esc(cfg('app.privacy_version'))?>.</p>
<h2>Responsable</h2><p><?=esc(cfg('legal.company'))?>, nombre comercial InnovaPro, NIF <?=esc(cfg('legal.tax_id'))?>. Domicilio: <?=esc(cfg('legal.address'))?>. Contacto para privacidad: <a href="mailto:<?=esc(cfg('legal.privacy_email'))?>"><?=esc(cfg('legal.privacy_email'))?></a>.</p>
<h2>Formulario y atención de solicitudes</h2><p>Recogemos nombre, teléfono y email para responder a tu consulta, asesorarte y concertar una demostración o informarte sobre compra, alquiler y financiación. El consentimiento del formulario autoriza esta atención y puede retirarse. No te suscribe a publicidad periódica.</p><p>La solicitud se almacena primero en una base de datos MariaDB/MySQL. Después enviamos una notificación mediante SMTP autenticado al personal autorizado. Si el correo falla, la solicitud permanece guardada y puede consultarse desde el panel privado.</p><p>Conservamos fecha, consentimiento y su versión, estado técnico del correo y metadatos de la solicitud: parámetros de campaña UTM, GCLID/WBRAID/GBRAID si existen, URL de entrada y referencia. Estos datos proceden de la solicitud actual; la aplicación no crea cookies de atribución propias ni guarda tu IP. El alojamiento puede generar registros técnicos que el responsable debe configurar con acceso y conservación limitados.</p>
<h2>Google Ads y Consent Mode</h2><p>La decisión sobre cookies y medición es independiente del consentimiento para responder al formulario. Puedes rechazar la medición y utilizar las tres vías de contacto.</p><p>Utilizamos Google Ads directamente con Consent Mode v2 avanzado. Sin interacción y al rechazar, ad_storage, ad_user_data, ad_personalization y analytics_storage permanecen denegados. La etiqueta puede enviar señales de conversión sin cookies publicitarias, con información técnica y de la página, conforme al comportamiento de Google.</p><p>Al aceptar, permitimos almacenamiento publicitario y datos de usuario para medición. La personalización publicitaria y el almacenamiento de Analytics siguen denegados. No usamos GA4, Google Tag Manager, Meta Pixel ni grabación de sesiones.</p>
<h2>Conversiones mejoradas del formulario</h2><p>Solo tras guardar el formulario y cuando ad_user_data está concedido, normalizamos el email y el teléfono y enviamos a Google sus valores transformados mediante SHA-256 para mejorar la medición de conversiones. No enviamos nombre ni dirección. El hash no convierte los datos personales en anónimos. Sin aceptación o tras rechazo no enviamos estos datos a Google; la conversión estándar puede seguir enviando una señal sin cookies.</p><p>Los clics en teléfono y WhatsApp se miden por separado, sin datos de conversiones mejoradas. Un clic no acredita una llamada realizada ni un mensaje enviado. WhatsApp solo se abre al pulsar su enlace y aplica sus propias condiciones.</p>
<h2>Destinatarios y proveedores</h2><p>Acceden a las solicitudes el personal autorizado de InnovaPro y los proveedores necesarios de alojamiento y correo bajo los acuerdos correspondientes. Google Ireland Limited y otras entidades de Google pueden tratar la medición, incluidas transferencias internacionales conforme a las condiciones y mecanismos del servicio contratado. Consulta <a href="https://policies.google.com/privacy" target="_blank" rel="noopener noreferrer">la privacidad de Google</a>. No vendemos los datos.</p>
<p>Alojamiento: <?=esc(cfg('legal.hosting_provider') ?: 'PENDIENTE DE CONFIRMACIÓN: proveedor y ubicación')?>. Proveedor SMTP: <?=esc(cfg('legal.email_provider') ?: 'PENDIENTE DE CONFIRMACIÓN: proveedor y ubicación')?>.</p>
<h2>Conservación</h2><p><?=esc(cfg('legal.retention_policy') ?: 'PENDIENTE DE CONFIRMACIÓN: el responsable debe establecer el plazo concreto de conservación de solicitudes y los criterios de revisión y supresión antes de publicar esta política.')?></p>
<h2>Derechos</h2><p>Puedes solicitar acceso, rectificación, supresión, oposición, limitación o portabilidad cuando proceda, y retirar el consentimiento en <?=esc(cfg('legal.privacy_email'))?>. Solo pediremos información adicional de identidad si es necesaria. Puedes reclamar ante la <a href="https://www.aepd.es/" target="_blank" rel="noopener noreferrer">Agencia Española de Protección de Datos</a>.</p><p>No adoptamos decisiones automatizadas con efectos jurídicos. Cambia tu preferencia publicitaria desde «Configurar cookies» en el footer. La retirada no elimina retroactivamente tratamientos anteriores.</p>
</main><?php site_footer(); ?>
