<?php
declare(strict_types=1);
require __DIR__ . '/includes/bootstrap.php';
require __DIR__ . '/includes/layout.php';
page_head('Política de privacidad | InnovaPro'); site_header(false);
?>
<main id="contenido" class="wrap legal-page"><a href="/">← Volver a la landing</a><h1>Política de privacidad</h1><p>Información de demo.innovapro.es. Versión <?=esc(cfg('app.privacy_version'))?>.</p>
<h2>Responsable</h2><p><?=esc(cfg('legal.company'))?>, nombre comercial InnovaPro, NIF <?=esc(cfg('legal.tax_id'))?>. Domicilio: <?=esc(cfg('legal.address'))?>. Contacto para privacidad: <a href="mailto:<?=esc(cfg('legal.privacy_email'))?>"><?=esc(cfg('legal.privacy_email'))?></a>.</p>
<h2>Formulario y atención de solicitudes</h2><p>Recogemos nombre, teléfono y email para responder a tu consulta, asesorarte y concertar una demostración o informarte sobre compra, alquiler y financiación. La base jurídica es tu consentimiento para atender esta consulta (artículo 6.1.a del RGPD), que se recoge mediante una casilla no premarcada y que puedes retirar en cualquier momento, sin afectar a la licitud de lo ya realizado. Los tres datos solicitados son necesarios para poder responder y contactar contigo; si no los facilitas no podremos tramitar el formulario. Esta solicitud no te suscribe a comunicaciones publicitarias periódicas.</p><p>La solicitud se almacena primero en una base de datos MariaDB/MySQL. Después enviamos una notificación mediante SMTP autenticado al personal autorizado. Si el correo falla, la solicitud permanece guardada y puede consultarse desde el panel privado.</p><p>Conservamos fecha, consentimiento y su versión, estado técnico del correo y metadatos de la solicitud: parámetros de campaña UTM, GCLID/WBRAID/GBRAID si existen, URL de entrada y referencia. Estos datos proceden de la solicitud actual; la aplicación no crea cookies de atribución propias ni guarda tu IP. El alojamiento puede generar registros técnicos que el responsable debe configurar con acceso y conservación limitados.</p>
<h2>Google Ads y Consent Mode</h2><p>La elección sobre cookies publicitarias y conversiones mejoradas es independiente de la autorización para responder al formulario. Puedes rechazar las cookies opcionales y seguir utilizando el formulario, el teléfono o WhatsApp. El uso de cookies publicitarias y de datos de contacto para conversiones mejoradas requiere tu aceptación específica en el aviso de cookies.</p><p>Utilizamos Google Ads directamente con Consent Mode v2 avanzado. Sin interacción y al rechazar, ad_storage, ad_user_data, ad_personalization y analytics_storage permanecen denegados. La etiqueta puede enviar a Google señales técnicas de consentimiento y de conversión sin cookies publicitarias, incluso si ignoras o rechazas el aviso. Estas señales pueden incluir información del dispositivo, referencia, hora y URL de la página, conforme a la documentación de Google; no incorporan el email ni el teléfono del formulario como datos para conversiones mejoradas.</p><p>Al aceptar, permitimos almacenamiento publicitario y datos de usuario para medición. La personalización publicitaria y el almacenamiento de Analytics siguen denegados. No usamos GA4, Google Tag Manager, Meta Pixel ni grabación de sesiones.</p>
<h2>Conversiones mejoradas del formulario</h2><p>Solo tras guardar el formulario y cuando ad_user_data está concedido, normalizamos el email y el teléfono y enviamos a Google sus valores transformados mediante SHA-256 para mejorar la medición de conversiones. No enviamos nombre ni dirección. El hash no convierte los datos personales en anónimos. Sin aceptación o tras rechazo no enviamos estos datos a Google; la conversión estándar puede seguir enviando una señal sin cookies.</p><p>Los clics en teléfono y WhatsApp se miden por separado, sin datos de conversiones mejoradas. Un clic no acredita una llamada realizada ni un mensaje enviado. WhatsApp solo se abre al pulsar su enlace y aplica sus propias condiciones.</p>
<h2>Destinatarios y proveedores</h2><p>Acceden a las solicitudes el personal autorizado de InnovaPro y los proveedores necesarios de alojamiento y correo bajo los acuerdos correspondientes. Google Ireland Limited y las entidades de Google que correspondan tratan los datos técnicos de la medición publicitaria. Google informa de posibles transferencias internacionales y de mecanismos como el Marco de Privacidad de Datos UE-EE. UU. o las cláusulas contractuales tipo, según corresponda. Consulta <a href="https://business.safety.google/intl/es/adsdatatransfers/" target="_blank" rel="noopener noreferrer">la información de Google sobre transferencias internacionales</a> y su <a href="https://policies.google.com/privacy" target="_blank" rel="noopener noreferrer">Política de Privacidad</a>. No comercializamos tus datos de contacto.</p>
<p>Para prestar el servicio intervienen las siguientes categorías de destinatarios: proveedores de alojamiento web y bases de datos, proveedores de correo para notificar las solicitudes, y prestadores de medición publicitaria (Google). Los prestadores de alojamiento y correo deben tratar los datos con las garantías y acuerdos que les correspondan como encargados del tratamiento. La identidad y ubicación de los proveedores técnicos concretos se verifica según los contratos de servicio.</p>
<?php if (cfg('legal.hosting_provider') || cfg('legal.email_provider')): ?>
<p><?php if (cfg('legal.hosting_provider')): ?>Alojamiento: <?=esc(cfg('legal.hosting_provider'))?>. <?php endif; ?><?php if (cfg('legal.email_provider')): ?>Correo de notificaciones: <?=esc(cfg('legal.email_provider'))?>.<?php endif; ?></p>
<?php endif; ?>
<h2>Conservación</h2><p><?=esc(cfg('legal.retention_policy') ?: 'Los datos se conservarán mientras sean necesarios para atender la solicitud y, posteriormente, durante los plazos de prescripción de las responsabilidades legales que correspondan. Cuando dejen de ser necesarios se suprimirán o, en su caso, se bloquearán conforme a la ley.')?></p>
<h2>Derechos</h2><p>Puedes solicitar acceso, rectificación, supresión, oposición, limitación o portabilidad cuando proceda, y retirar el consentimiento en <?=esc(cfg('legal.privacy_email'))?>. Solo pediremos información adicional de identidad si es necesaria. Puedes reclamar ante la <a href="https://www.aepd.es/" target="_blank" rel="noopener noreferrer">Agencia Española de Protección de Datos</a>.</p><p>No adoptamos decisiones automatizadas con efectos jurídicos. Cambia tu preferencia publicitaria desde «Configurar cookies» en el footer. La retirada no elimina retroactivamente tratamientos anteriores.</p>
</main><?php site_footer(); ?>
