<?php
declare(strict_types=1);
require __DIR__.'/../src/bootstrap.php';
require __DIR__.'/../src/view.php';
use function Innova\{head,header_view,footer_view,cfg,esc,phone_link,whatsapp_button};
$requestId = bin2hex(random_bytes(16));
head('Depilación profesional · Compra, alquiler y financiación | InnovaPro',true);
header_view();
?>
<main id="contenido">
<section class="hero wrap" aria-labelledby="hero-title">
  <div class="hero-copy"><p class="eyebrow">Tecnología SHR y láser diodo · Gama InnovaPro</p><h1 id="hero-title"><span>Equipos de depilación profesional</span> para hacer crecer tu centro</h1><p class="hero-description">Te ayudamos a elegir el equipo adecuado, probarlo y decidir entre <strong>compra, alquiler o financiación.</strong></p></div>
  <div class="hero-visual"><img src="/assets/img/gama-shr.webp" srcset="/assets/img/gama-shr-small.webp 800w, /assets/img/gama-shr.webp 1500w" sizes="(max-width: 760px) 100vw, 64vw" width="1500" height="871" fetchpriority="high" alt="Gama de equipos de depilación profesional InnovaPro"><p class="image-caption">Una gama de soluciones. Un equipo que te ayuda a elegir.</p></div>
  <aside class="hero-contact" id="contacto" aria-labelledby="form-title"><p class="commercial-options">Compra · Alquiler · Financiación</p><div class="form-card"><p class="eyebrow">Demostración gratuita</p><h2 id="form-title">Prueba el equipo <br> antes de decidir</h2><p class="form-intro">No necesitas saber qué modelo elegir. Te asesoramos.</p>
  <form id="lead-form" method="post" action="/api/lead.php" novalidate>
    <input type="hidden" name="request_id" value="<?=esc($requestId)?>">
    <label class="field" for="name">Nombre<input id="name" name="name" autocomplete="name" maxlength="120" required aria-describedby="error-name"><span class="field-error" id="error-name"></span></label>
    <label class="field" for="phone">Teléfono<input id="phone" name="phone" type="tel" autocomplete="tel" inputmode="tel" maxlength="40" required aria-describedby="error-phone"><span class="field-error" id="error-phone"></span></label>
    <label class="field" for="email">Correo electrónico<input id="email" name="email" type="email" autocomplete="email" maxlength="254" required aria-describedby="error-email"><span class="field-error" id="error-email"></span></label>
    <div class="privacy-check"><input id="privacy" type="checkbox" name="privacy" value="1" required aria-describedby="error-privacy"><label for="privacy">He leído la <a href="/privacidad.php" target="_blank" rel="noopener noreferrer">Política de Privacidad</a> y autorizo a InnovaPro a utilizar mis datos para atender esta solicitud.</label></div><span class="field-error" id="error-privacy"></span>
    <p class="form-legal">Responsable: <?=esc(cfg('legal.company'))?>. Puedes ejercer tus derechos en <?=esc(cfg('legal.privacy_email'))?>. Esta solicitud no te suscribe a publicidad.</p>
    <button class="button button-primary form-submit" type="submit">Solicitar mi demo gratuita <span aria-hidden="true">→</span></button>
    <p id="form-status" class="form-status" role="status" aria-live="polite" tabindex="-1"></p>
    <noscript><p>También puedes llamar al <?=esc(cfg('contact.phone_display'))?>. El formulario funciona sin JavaScript y mostrará la confirmación del servidor.</p></noscript>
  </form><div class="form-alternatives"><a class="button button-secondary" href="<?=esc(phone_link())?>" data-contact="phone">Llamar <span aria-hidden="true">↗</span></a><?=whatsapp_button()?></div><p class="form-footnote">Para centros y profesionales de estética.</p></div></aside>
</section>
<section class="products wrap section" aria-labelledby="products-title"><div class="section-heading"><p class="eyebrow">Cuatro configuraciones, una misma gama</p><h2 id="products-title">Encuentra el equipo<br> que mejor encaja con tu centro</h2></div>
<div class="product-grid">
  <article class="product"><h3>SHR X Ultra</h3><div class="product-picture"><img src="/assets/img/shr-ultra.webp" alt="Equipo SHR X Ultra" width="500" height="849" loading="lazy"></div><h4>La opción más completa</h4><p class="product-tech">Depilación + RF + fotorrejuvenecimiento + Nd:YAG</p><p>Diferentes tecnologías en un único equipo para ampliar tu oferta de tratamientos.</p></article>
  <article class="product"><h3>SHR Xn</h3><div class="product-picture"><img src="/assets/img/shr-xn.webp" alt="Equipo SHR Xn" width="530" height="680" loading="lazy"></div><h4>Depilación + Nd:YAG</h4><p class="product-tech">Depilación SHR y tecnología Nd:YAG</p><p>Combina depilación profesional con las posibilidades adicionales del Nd:YAG.</p></article>
  <article class="product"><h3>SHR Xe</h3><div class="product-picture"><img src="/assets/img/shr-xe.webp" alt="Equipo SHR Xe" width="530" height="656" loading="lazy"></div><h4>Depilación y tratamientos faciales</h4><p class="product-tech">Depilación + E-Light / radiofrecuencia</p><p>Una configuración versátil para depilación y otros tratamientos estéticos.</p></article>
  <article class="product"><h3>SHR 808</h3><div class="product-picture"><img src="/assets/img/shr-808.webp" alt="Equipo SHR 808" width="500" height="968" loading="lazy"></div><h4>Especialización en depilación láser</h4><p class="product-tech">Láser diodo 808 nm</p><p>Una solución centrada específicamente en la depilación profesional.</p></article>
</div><div class="inline-cta"><div><strong>¿No sabes cuál necesita tu centro?</strong><p>Antes de invertir, pruébalo. Te ayudamos a elegir.</p></div><a href="#contacto" class="button button-gold" data-form-focus>Solicitar demo <span aria-hidden="true">→</span></a></div></section>
<section class="modalities wrap section" aria-labelledby="modalities-title"><div class="section-heading"><p class="eyebrow">Distintas formas de empezar</p><h2 id="modalities-title">Elige cómo incorporar<br> tecnología a tu centro</h2></div><div class="modality-grid">
<article><span class="small-label">Compra de aparatología</span><h3>Tu equipo, tu inversión</h3><p>Elige el equipo que mejor encaja con tu centro, con asesoramiento para aprovechar sus posibilidades.</p><a href="#contacto" data-form-focus>Consultar compra <span aria-hidden="true">→</span></a></article>
<article><span class="small-label">Alquiler</span><h3>Otra forma de empezar</h3><p>Consulta la disponibilidad y las condiciones de alquiler de nuestros equipos de depilación profesional.</p><a href="#contacto" data-form-focus>Consultar alquiler <span aria-hidden="true">→</span></a></article>
<article><span class="small-label">Financiación</span><h3>Planifica tu inversión</h3><p>Te informamos sobre las opciones de financiación disponibles para incorporar tecnología a tu negocio.</p><a href="#contacto" data-form-focus>Consultar financiación <span aria-hidden="true">→</span></a></article>
</div><p class="modalities-note"><strong>¿Ya tienes aparatología?</strong> Pregúntanos también por el Plan Renove y las opciones de explotación compartida. Disponibilidad y condiciones según equipo y valoración de tu caso.</p></section>
<section class="support wrap section" aria-labelledby="support-title"><div><p class="eyebrow">Tienes un equipo detrás</p><h2 id="support-title">No compras<br> solo un equipo</h2><dl class="support-list"><div><dt>Asesoramiento</dt><dd>Elegimos contigo la tecnología adecuada para las necesidades de tu centro.</dd></div><div><dt>Formación</dt><dd>Aprende a trabajar con tu equipo y a aprovechar sus posibilidades.</dd></div><div><dt>Servicio técnico</dt><dd>Un equipo preparado para ayudarte cuando lo necesites.</dd></div><div><dt>Acompañamiento</dt><dd>Seguimos a tu lado después de instalar el equipo.</dd></div></dl><a class="text-link" href="#contacto" data-form-focus>Habla con nuestro equipo <span aria-hidden="true">→</span></a></div><img src="/assets/img/acompanamiento.webp" width="1050" height="791" loading="lazy" alt="Demostración de un equipo de depilación InnovaPro por una profesional"></section>
<?php if(cfg('content.testimonials_enabled')):?>
<section class="testimonials section" aria-labelledby="testimonials-title"><div class="wrap"><p class="eyebrow">Experiencias con InnovaPro</p><h2 id="testimonials-title">Quienes trabajan con nosotros<br> lo cuentan mejor</h2><div class="testimonial-grid"><figure><blockquote>“No solo venden aparatos de estética, acompañan, asesoran y se implican de verdad en tu crecimiento.”</blockquote><figcaption>Mara Manca</figcaption></figure><figure><blockquote>“Llevo 25 años o más trabajando con ellos y nunca me han fallado.”</blockquote><figcaption>Loli</figcaption></figure><figure><blockquote>“Cualquier duda la solucionan con rapidez, la comunicación es excelente y siempre están disponibles para ayudarte.”</blockquote><figcaption>Ana</figcaption></figure></div></div></section>
<?php endif;?>
<section class="commitment section"><div class="wrap"><h2>Compromiso total</h2><div class="commitment-grid"><article><h3>Soporte técnico</h3><p>Atención profesional para resolver dudas y acompañarte en el uso del equipo.</p></article><article><h3>Consumibles</h3><p>Repuestos y consumibles adecuados para mantener tu aparatología.</p></article><article><h3>Garantía</h3><p>Información clara sobre la cobertura y las condiciones aplicables a tu equipo.</p></article></div></div></section>
<section class="final-cta wrap section" aria-labelledby="final-title"><div><p class="eyebrow">Da el siguiente paso</p><h2 id="final-title">Prueba antes de decidir.</h2><p>Solicita tu demostración y descubre qué equipo encaja mejor con tu centro.</p></div><div class="final-actions"><a href="#contacto" class="button button-primary" data-form-focus>Solicitar mi demo gratuita <span aria-hidden="true">→</span></a><div><a href="<?=esc(phone_link())?>" data-contact="phone">Llamar</a><span aria-hidden="true"> · </span><?=whatsapp_button('text-link')?></div></div></section>
</main>
<?php footer_view(true); ?>
