-- MariaDB 10.6+ / MySQL 8.0+. Base nueva, InnoDB; created_at/email_sent_at en UTC.
CREATE TABLE leads (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    request_id CHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    request_hash CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    nombre VARCHAR(120) NOT NULL,
    telefono VARCHAR(40) NOT NULL,
    email VARCHAR(254) NOT NULL,
    consent_rgpd TINYINT(1) NOT NULL,
    consent_version VARCHAR(64) NOT NULL,
    gclid VARCHAR(512) NULL,
    wbraid VARCHAR(512) NULL,
    gbraid VARCHAR(512) NULL,
    utm_source VARCHAR(200) NULL,
    utm_medium VARCHAR(200) NULL,
    utm_campaign VARCHAR(200) NULL,
    utm_term VARCHAR(200) NULL,
    utm_content VARCHAR(200) NULL,
    landing_url VARCHAR(2048) NOT NULL,
    referrer VARCHAR(2048) NULL,
    email_status ENUM('pending','sent','error') NOT NULL DEFAULT 'pending',
    email_attempts INT UNSIGNED NOT NULL DEFAULT 0,
    email_last_error VARCHAR(64) NULL,
    email_sent_at DATETIME NULL,
    CONSTRAINT uq_leads_request UNIQUE (request_id),
    CONSTRAINT chk_consent CHECK (consent_rgpd = 1),
    CONSTRAINT chk_mail_sent CHECK ((email_status = 'sent' AND email_sent_at IS NOT NULL) OR (email_status <> 'sent' AND email_sent_at IS NULL)),
    INDEX idx_created_at (created_at),
    INDEX idx_email (email),
    INDEX idx_mail_created (email_status, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
